/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PredictionHistory = IDL.Record({
  'predictedValue' : IDL.Float64,
  'modelName' : IDL.Text,
  'inputFeatures' : IDL.Text,
  'timestamp' : IDL.Int,
  'confidence' : IDL.Float64,
});

export const idlService = IDL.Service({
  'clearPredictions' : IDL.Func([], [], []),
  'getPredictions' : IDL.Func([], [IDL.Vec(PredictionHistory)], ['query']),
  'savePrediction' : IDL.Func(
      [IDL.Int, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PredictionHistory = IDL.Record({
    'predictedValue' : IDL.Float64,
    'modelName' : IDL.Text,
    'inputFeatures' : IDL.Text,
    'timestamp' : IDL.Int,
    'confidence' : IDL.Float64,
  });
  
  return IDL.Service({
    'clearPredictions' : IDL.Func([], [], []),
    'getPredictions' : IDL.Func([], [IDL.Vec(PredictionHistory)], ['query']),
    'savePrediction' : IDL.Func(
        [IDL.Int, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };